index:
   path: /inicio
   controller: App\Controller\HomeController::index
   
animales:
   path: /animales/{nombre}/{apellidos}
   controller: App\Controller\HomeController::animales
   defaults: {nombre: 'Nmbre por defectoo', apellidos: 'Apellidicos por defecto'}
   methods: [GET]
   requirements:
       nombre: '[a-z,A-Z ]+'
       apellidos: '[a-z,A-Z ]+'
       # hay un espacio en blanco al final de la Z, para permitir espacios en blanco
       
redirigir:
   path: /redirigir
   controller: App\Controller\HomeController::redirigir

