index:
   path: /inicio
   controller: App\Controller\HomeController::index
   
animales:
   path: /animales/{nombre}/{apellidos}
   controller: App\Controller\HomeController::animales
   defaults: {nombre: 'Nmbre por defectoo', apellidos: 'Apellidicos por defecto'}
   methods: [GET]
   requirements:
       nombre: '[a-z,A-Z ]+'
       apellidos: '[a-z,A-Z ]+'
       # hay un espacio en blanco al final de la Z, para permitir espacios en blanco
       
       # Para listar las rutas desde consola con: php bin/console debug:router
       
redirigir:
   path: /redirigir
   controller: App\Controller\HomeController::redirigir


       
animal_index:
   path: /animal/index
   controller: App\Controller\AnimalController::index
   
animal_save:
   path: /animal/save
   controller: App\Controller\AnimalController::save
   
animal_detail:
   path: /animal/{id}
   controller: App\Controller\AnimalController::animal
   
animal_detail2:
   path: /animal2/{id}
   controller: App\Controller\AnimalController::animal2
   
animal_update:
   path: /animal/update/{id}
   controller: App\Controller\AnimalController::update
animal_delete:
   path: /animal/delete/{id}
   controller: App\Controller\AnimalController::delete